name: uikit_bindings
description: "Bindings of UIKit components for Flutter using FFI."
version: 0.0.1
homepage: https://github.com/orestesgaolin/uikit_bindings
repository: https://github.com/orestesgaolin/uikit_bindings
issue_tracker: https://github.com/orestesgaolin/uikit_bindings/issues

platforms:
  ios:

topics:
  - flutter
  - ios
  - uikit
  - ffi
  - bindings

environment:
  sdk: ^3.10.4
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  objective_c: ^9.2.2

dev_dependencies:
  ffigen: ^20.1.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  logging: ^1.3.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
